### ISSUE TITLE
System Notification Management

### ISSUE THREAD

**Issue by Calebgisa72** [atlp-rwanda/knights-ecomm-be#101]
Description
As a platform user (vendor or buyer), I want to be notified of every significant event or action related to the products on the e-commerce platform in real-time. This includes notifications for actions such as product addition, expiration, purchase, discounting, etc. This feature will ensure that users stay informed and engaged with the platform's activities.

Acceptance Criteria
- Implement an API endpoint for notifications
- Validate user's authentication and authorization
- Send notifications in real-time using Socket.IO
- Display the number of new and unread notifications on the notification icon
- Ensure users can view all available notifications
- Send notifications to the correct user (seller/buyer) based on the action performed
- Implement appropriate error handling and responses

 Developer Notes
- Define the API endpoint and request/response payloads for notifications
- Implement authentication and authorization checks for user access
- Use Socket.IO to send real-time notifications to users
- Update the notification icon to display the count of new and unread notifications
- Develop a user interface to display all available notifications
- Ensure notifications are sent to the appropriate user based on the action (e.g., notify a seller when their product is bought)
- Handle edge cases, such as failed notification delivery or unauthorized access
- Write unit tests to cover different scenarios and edge cases
- Write clear API documentation for the resulting endpoint

Definition of Done
- Notification API endpoint is implemented and functional
- User authentication and authorization are validated
- Real-time notifications are sent using Socket.IO
- Notification icon displays the number of new and unread notifications
- Users can view all available notifications
- Notifications are sent to the correct user (seller/buyer) based on the action performed
- Appropriate error handling and responses are implemented
- Unit tests are written and passing
- API documentation for the resulting endpoint is completed

**Comment by faid-terence** [comment]
Nice Work @Calebgisa72 
Now Also attach the implementation plan !

**Comment by Calebgisa72** [comment]
The Implementation Plan:

1. Create a New Branch
Task: Create a new branch for this feature.
The branch will be called "feat-notifications"

2. Creating entities needed to work on this task
Task: Creating a Notification database
Steps:
Creating a notification entity that collects all the information of a user notification.
Creating notification item entity which will collect all the notifications in the system.

3. Set Up Notification Infrastructure
Task: Set up Socket.IO for real-time notifications.
Steps:
Install and configure Socket.IO in the backend.
Set up a Socket.IO server to handle real-time communication.

4.  Notification Service
Task: Create a service for managing notifications.
Steps:
Implement functions to create, store, and get notifications.
Ensuring notifications are targeted to the correct users (vendor/buyer).

5. Implement API Endpoint
Task: Develop an API endpoint for sending notifications.
Steps:
Create a POST endpoint /send notification.
Validate user's authentication and authorization.
Use the notification service to send notifications.
Implement appropriate error handling and responses.

6. Update Notification Icon
Task: Update the number of new and unread notifications.
Steps:
Modify the field in the database that contains the number of unread notification.
Update the field in real-time as new notifications are received.

7. Handle Edge Cases
Task: Implement error handling for various scenarios.
Steps:
Handle unauthorized access.
Ensure proper handling of notification delivery failures.

8. Write Unit Tests
Task: Create unit tests for the notification service and API endpoint.
Steps:
Test the notification creation and sending logic.
Test the API endpoint with different scenarios (valid actions, invalid actions, unauthorized access).
Test the real-time functionality using Socket.IO.

9. Code Review and Testing
Task: Conduct a code review and run tests.
Steps:
Submit a pull request for review.
Address any feedback from the code review.
Ensure all tests pass successfully.

10. Write Documentation
Task: Document the API and the notification system.
Steps:
Write API documentation for the notification endpoint.
