### ISSUE TITLE
Feat: Register User (Vendors & Buyers)

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#39]
## Description

As a vendor or buyer, I want to be able to register an account on the e-commerce platform so that I can access the respective features and functionalities.

The registration process should allow users to sign up as either a vendor or a buyer, and capture relevant information such as name, email, password, and any additional details required for each user type.

### Acceptance Criteria

- [x] Implement a user registration API endpoint
- [x] Validate user input (e.g., email, password, user type)
- [x] Check for existing users (email uniqueness)
- [x] Hash and store user passwords securely
- [x] Create user records in the database with appropriate user types (vendor or buyer)
- [x] Return appropriate success or error responses
- [x] Implement input sanitization

## Developer Notes

- Design the user registration data model and database schema
- Define the API endpoint and request/response payloads
- Implement input validation and sanitization measures
- Use a secure password hashing algorithm (e.g., bcrypt, argon2)
- Implement email user verification
- Write unit tests to cover different scenarios and edge cases
- Write clear API documentation for resulting endpoints

## Related Issues

- #40   
- #41
- #46  

## Definition of Done

- User registration API endpoint is implemented and functional
- User input validation and sanitization measures are in place
- Passwords are securely hashed and stored
- User records are created in the database with appropriate user types
- Appropriate success and error responses are returned
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- All created endpoints are documented

## Implimentation plan

**1. Deliverables at the End of the Project**
Functionality:

-  Users can register with their details and get stored in the database.
 Technical Considerations:

- The implementation plan will consider the manager's provided document 

**2. Data Flow / Flowchart / Pseudocode / ERD Diagrams**
Tools:

- **Node.js:**
- Backend Server: Node.js will serve as the foundation for our backend server, handling user requests for password reset, generating tokens, and interacting with the database.

**- PostgreSQL:**
- Database: PostgreSQL will store your user data, including email addresses. 

**TypeORM:**

- Object-Relational Mapper (ORM): TypeORM acts as an ORM, simplifying interactions between your Node.js application and the PostgreSQL database. It allows you to write code using JavaScript classes and methods that map to database tables and queries.

**3. Schedule of Implementation**
Breakdown:
**Tuesday (April 30):**

- **Backend Setup:**

- Installed Node.js and set up your development environment.
- Installed TypeORM and configured your database connection (PostgreSQL).

- **Initial Routes and Controllers:**

 - Defined basic routes for handling user registration (e.g., /user/register).
 - Created controller functions to handle these routes.

**Wednesday (May 1st):**

- **Code Refactoring:**
- Reviewed and refactored the code based on your colleague's suggestions.
- Improved code structure, readability, and maintainability.
- Added comments to explain the code functionality.
- **Version Control (Git):**
- Committed your code changes to a version control system like Git.
- Pushed your code to a remote repository like GitHub.

**4. Dependencies/Foreseen Blockers**
Learning  typeOrm

**5. External Services or Libraries to be Used**

Potential Libraries:

- Consider using a library for sending emails (e.g., Nodemailer).
- A secure password hashing library like bcrypt or argon2 is recommended.

**6. How This Fits with Existing Work (Optional)**

- This implementation builds upon the previously developed work with the team..
- Ensure data models and API endpoints are compatible for a smooth integration.

**Comment by faid-terence** [comment]
@maxCastro1 !
Please attach your implementation Plan
