### ISSUE TITLE
Feat: Manage a Product

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#48]
### Description

As a vendor, I should be able to perform Create, Read, Update, and Delete (CRUD) operations on products in my collection, so that I can effectively manage my inventory and make products available for sale to buyers.

#### Create

- [x] Implement a seller product creation API endpoint
- [x] Validate the requesting user's role as a seller
- [x] Validate the request body (price, name, category, expiry date, bonus, etc.)
- [x] Check if the target item already exists in the seller's collection
- [x] If the item does not exist, add it to the seller's collection
- [x] If the item exists, return a response suggesting an update of stock levels
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization
- [x] Ensure the product has a reference to the associated seller
- [x] Handle product images as reference URLs in the database (4 - 8 images)

#### Read

- [x] Implement an API endpoint for retrieving a seller's product collection
- [x] Validate the requesting user's role as a seller
- [x] Retrieve and return the list of products associated with the seller
- [x] Implement pagination and filtering options (if necessary)
- [x] Implement error handling and appropriate response messages

#### Update

- [x] Implement an API endpoint for updating a seller's product details
- [x] Validate the requesting user's role as a seller
- [x] Validate the request payload (product ID, updated fields)
- [x] Retrieve the product from the database based on the provided product ID
- [x] Ensure the product belongs to the requesting seller
- [x] Update the product details in the database
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

#### Delete

- [x] Implement an API endpoint for deleting a seller's product
- [x] Validate the requesting user's role as a seller
- [x] Validate the request payload (product ID)
- [x] Retrieve the product from the database based on the provided product ID
- [x] Ensure the product belongs to the requesting seller
- [x] Delete the product from the database
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

### Developer Notes

- Document with Swagger
- All inputs should be validated for sanity
- Only reference URLs may be stored in the database for the case of file uploads
- The product should have a reference to the seller

### Related Issues

- #45 

### Definition of Done

- CRUD API endpoints for seller product management are implemented and functional
- Appropriate responses are sent to the requesting client based on scenarios
- Validation checks are implemented for request body and user role
- Product images are handled as reference URLs in the database
- Products have a reference to the associated seller
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation with Swagger is completed

**Comment by aimedivin** [comment]
## 1. Deliverables at the end of the project.

By the end, vendors can easily manage products. They'll create, view, update, and delete products. We'll ensure only the right vendor (product owner) can make changes. Swagger helps us document everything neatly.

#### DEV NOTE (REQUIRED)
Document code using Swagger

## 2. Data flow / Flowchart / pseudocode / ERD diagrams
#### ER Diagram
![diagram-export-5-9-2024-4_34_25-PM](https://github.com/atlp-rwanda/knights-ecomm-be/assets/82057476/f18c0ebf-e337-41c2-b268-4b1063fe7c5e)


#### Determine the Environments (tools)
- Use Nodejs(expressJs)
- Use Typescript
- Use Multer
- TypeORM (Postgres)

## 4. Schedule of implementation of the various parts
Below Tasks will be delivered by specified dates
- Implementation plan by Thursday (9th/5/2024)
- API Implementation by Thursday (9th/5/2024)
- API Documentation and Unit Testing by Friday (10th/ 5/2024) 

## 5. Dependencies/Foreseen blockers from team members
None

## 6. External services or libraries to be used.
<img src="https://upload.wikimedia.org/wikipedia/commons/b/b0/Cloudinary_logo_blue_0720_2x.png" alt="Cloudinary_logo" width="200">  &nbsp;&nbsp;&nbsp;&nbsp;  <img src="https://github.com/atlp-rwanda/knights-ecomm-be/assets/82057476/a42d3196-3140-4d16-8705-fa991f1492f9" alt="images" width="200">

**Comment by faid-terence** [comment]
@aimedivin  and @MC-Knight !
Your implementation plan looks good , just one question
Are you implementing the task in same branch or separate branch ??

**Comment by MC-Knight** [comment]
@faid-terence on same branch

**Comment by faid-terence** [comment]
Alright !! You can start working
