### ISSUE TITLE
Feat: Product Availability

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#49]
### Description

As a vendor, I should be able to mark a product as available or unavailable manually, so that buyers can view and purchase the available products. Products may need to be marked as unavailable due to reasons such as expiry date or out-of-stock situations.

### Acceptance Criteria

- [x] Implement an API endpoint for updating product availability
- [x] Validate the requesting user's role as a vendor
- [x] Validate the request payload (product ID, availability status)
- [x] Retrieve the product from the database based on the provided product ID
- [x] Ensure the product belongs to the requesting vendor
- [x] Update the product availability status in the database
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

### Developer Notes

- Document the API endpoint with Swagger
- Define the request payload structure for updating product availability
- Implement necessary validation checks for the request payload
- Update the product availability status in the database
- Handle scenarios where the product does not exist or does not belong to the requesting vendor
- Write unit tests to cover different scenarios and edge cases

### Related Issues

- #48 

### Definition of Done

- API endpoint for updating product availability is implemented and functional
- Validation checks are implemented for the requesting user's role and request payload
- Product availability status is updated in the database
- Appropriate error handling and response messages are implemented
- Input sanitization measures are in place
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation with Swagger is completed

**Comment by Ndevu12** [comment]
Implementation Plan for Feature: Product Availability

1. ### Expected Outcome

Upon the closure of this issue, vendors will have the ability to manually manage the availability status of their products. This will allow vendors to mark products as available or unavailable based on factors such as stock levels or expiry dates. As a result, buyers will have an accurate view of product availability, improving the overall user experience and potentially increasing sales.

2. ### Input Validation

- We will implement robust input validation to ensure that the request payload contains a valid availability property. This will help to maintain data integrity and provide clear error messages to the client if the input is invalid.

3. ### Secure Data Retrieval

- Before all, we will verify if the user is authorized by using **_isTokenValid middleware_** which verify token validity.
- We will securely retrieve the product record from the database using the productId provided in the request. We will also verify that **_the authenticated user is the owner of the product_** before allowing the update to proceed.

4. ### API Endpoint Definition

- We will define a new PUT endpoint /products/:productId/availability. This endpoint will allow vendors to update the availability status of a specific product.

5. ### Error Handling and Response

- We will implement comprehensive error handling to catch any potential issues during the execution of the endpoint. This will include handling for common scenarios such as the product not being found, the user not having permission to update the product, and unexpected server errors. We will provide clear and helpful error messages in the response to assist the client in understanding any issues that occur.
