### ISSUE TITLE
Feat: Buyer should be able to see recommended products

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#69]
# Getting Recommended Product 

## Overview
In preparing this implementation plan, I aim to outline the steps required to develop a system that provides recommended products to buyers, i based on our purchase history. These recommended products will be associated with specific vendors.

### 1. Getting All Products
- **Objective**: Retrieve all products that  have purchased.
- **Implementation Steps**:
  - Implement an API endpoint to fetch all products associated signed in vendor.
  - Filter the retrieved products to eliminate duplicates.
  - Sort the products based on the number of times they have been purchased.

### 2. Filtering Retrieved Products and Showing Recommendations
- **Objective**: Determine recommended products based on purchase history and vendor association.
- **Implementation Steps**:
  - Analyze the retrieved records to identify products that  have been purchased more frequently than others.
  - Associate these products with their respective vendors.
  - Implement an API endpoint or functionality to display these recommended products to me.

### 3. Development Considerations
- **Endpoint Design**: Consider implementing a unique endpoint for the recommended products feature. This can help improve code organization and maintainability.

## Conclusion
By following the outlined implementation plan, I will be able to see recommended products associated with specific vendors based on purchase history. I'll ensure thorough testing and documentation to maintain the quality and usability of the system.

**Comment by faid-terence** [comment]
@elijahladdie 
Where's the implementation plan , you shouldn't start implementing without an implementation plan
