### ISSUE TITLE
Feat: Buyer should be able to search a product

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#70]
**Description**

The buyer should be able to search inside the site.

**Acceptance Criteria**

- [ ] The buyer can use name to search for product.
- [ ] Search results are reliable and relevant from the products record.
- [ ] Filtering and sorting options are supported by the search functionality.
- [ ] The implementation of pagination helps managing big result sets.

**Developer Notes**

- Provide a search feature for the product catalog service .
- Create API endpoints to manage requests for the product searches.
- Make use of effective querying and indexing strategies to provide the best search results.

**Related Issues**

#49 
#48 

**Definition of done**

- The creation and integration of API endpoints enables them to fulfill buyer requests for the product searches.
- The buyer can use name to search for the product.
- The search includes options for sorting and filtering.
- In order to manage big result sets, pagination is used.

**Comment by faid-terence** [comment]
@GSinseswa721 
Please comment your implementation plan below !

**Comment by GSinseswa721** [comment]
> @GSinseswa721 Please comment your implementation plan below !

Well noted!
