### ISSUE TITLE
Feat: Buyer should be able to manage their wish list

### ISSUE THREAD

**Issue by mukunzidd** [atlp-rwanda/knights-ecomm-be#71]
Description:

The backend needs to handle the addition of items to the buyer's wishlist, including storing the wishlist in the buyer's account and sending a confirmation message to the frontend.

Acceptance Criteria:
 

- [x] Implement a POST request endpoint to add an item to the buyer's wishlist.
- [x] When a POST request is made:
- [x] The item should be added to the buyer's wishlist.
- [x] The product details (name, price, image) should be retrieved from the database.
- [x] The updated wishlist should be stored with the buyer's entity and have a relationship with the buyer.
- [x] A confirmation message should be sent to the frontend to be displayed to the buyer.

Developer Notes:

- Validate that the buyer is logged in before processing the request.
- Implement logic to add the item to the buyer's wishlist.
- Retrieve the product details from the database based on the item being added.
- Store the updated wishlist in the buyer's account entity.

Related Issues:
Feat: Role-Based Access Control (RBAC) #45

Definition of Done:

- A POST request endpoint is implemented and functional for adding items to the buyer's wishlist.
- The item is successfully added to the buyer's wishlist.
- Product details (name, price, image) are retrieved from the database and associated with the item.
- The updated wishlist is stored in the buyer's account entity and has a proper relationship with the buyer.
- A confirmation message is sent to the frontend and displayed to the buyer.
- Buyer login validation is implemented to ensure only logged-in buyers can add items to their wishlist.

**Comment by faid-terence** [comment]
@Calebgisa72 
Can you use the [Eraser for ERD](https://eraser.io/) to show relationship between product, user and wishlist !
Also it's better to make Acceptance criteria in checkboxes . otherwise all is good.Apply the feedbacks

**Comment by Calebgisa72** [comment]
Implementation plan:

1. Creating a branch related to this issue and name it feat-wish-List
2. Creating a new entity that stores all the information of a product in a wish List
3. Create a many to one relationship between a wish list and a buyer
4. Implement a service for adding an item to a wish list
5. Implement a service for getting all the items a buyer added to a wish list
6. Implement a service for removing an item from buyer's wish list
7. Implement a service for removing all items a buyer added to a wish list
