### ISSUE TITLE
chore: API Documentation

### ISSUE THREAD

**Issue by MC-Knight** [atlp-rwanda/knights-ecomm-be#8]
**Why?**
API Documentation

**Description**
This issue involves setting up Swagger for API documentation. It includes documenting API endpoints, payloads, and authentication using swagger-jsdoc and swagger-ui-express libraries, along with their TypeScript definitions for type safety.
......................
**Acceptance**

- [ ] Set up Swagger or another API documentation tool
- [ ] Document API endpoints, request/response payloads, and authentication requirements

**Dev Notes**
Setting up Swagger documentation with help of these 

***Libraries and there corresponding types***

- swagger-jsdoc
- swagger-ui-express
- @types/swagger-jsdoc
- @types/swagger-ui-express

......................

**Comment by faid-terence** [comment]
@MC-Knight !
Please be descriptive 
`Why ?
Description
Dev Notes`

**Comment by MC-Knight** [comment]
@faid-terence !
descriptive How will I handle that?
