### ISSUE TITLE
Guest/Buyer should be able to manage to their cart

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-be#88]
### Description

As a buyer, I should be able to perform Create, Read, Update, and Delete (CRUD) operations on products in my cart, so that I can effectively manage my intended purchases and proceed to checkout when ready.

#### Create

- [x] Implement a buyer cart item addition API endpoint
- [x] Validate the requesting user's role as a buyer
- [x] Validate the request body (product ID, quantity)
- [x] Check if the target item already exists in the buyer's cart
- [x] If the item does not exist, add it to the buyer's cart with the specified quantity
- [x] If the item exists, update the quantity of the item in the cart
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

#### Read

- [x] Implement an API endpoint for retrieving a buyer's cart
- [x] Validate the requesting user's role as a buyer
- [x] Retrieve and return the list of products in the buyer's cart
- [x] Implement error handling and appropriate response messages

#### Update

- [x] Implement an API endpoint for updating a buyer's cart item details
- [x] Validate the requesting user's role as a buyer
- [x] Validate the request payload (product ID, updated quantity)
- [x] Retrieve the product from the cart based on the provided product ID
- [x] Ensure the product is in the requesting buyer's cart
- [x] Update the product quantity in the cart
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

#### Delete

- [x] Implement an API endpoint for removing a product from a buyer's car
- [x] Validate the requesting user's role as a buyer
- [x] Validate the request payload (product ID)
- [x] Retrieve the product from the cart based on the provided product ID
- [x] Ensure the product is in the requesting buyer's cart
- [x] Remove the product from the cart
- [x] Implement error handling and appropriate response messages for validation failures
- [x] Implement input sanitization

### Developer Notes

- Document with Swagger
- All inputs should be validated for sanity

### Related Issues

- #48 

### Definition of Done

- CRUD API endpoints for buyer cart management are implemented and functional
- Appropriate responses are sent to the requesting client based on scenarios
- Validation checks are implemented for request body and user role
- Quantity of each product in the cart is accurately tracked
- Cart has a reference to the associated buyer
- Unit tests are written and passing
- Code adheres to coding standards and best practices
- API documentation with Swagger is completed

**Comment by faid-terence** [comment]
@GSinseswa721 and @MC-Knight 
Please update the description and attach the implementation plan as well

**Comment by MC-Knight** [comment]
## 1. Deliverables at the end of the project.

By the end, buyers will be able to effectively manage their carts. They'll add, view, update, and remove products from their carts. We'll ensure that only the rightful buyer can make changes to their respective carts. Swagger will be used to document all these functionalities neatly, providing clear and interactive API documentation

#### DEV NOTE (REQUIRED)
Documenting code using Swagger

## 2. Data flow / Flowchart / pseudocode / ERD diagrams
#### ER Diagram
![diagram-export-5-22-2024-12_13_09-AM](https://github.com/atlp-rwanda/knights-ecomm-be/assets/78812884/ba78c59b-7988-42b1-b070-d2bcbfa6e766)

#### Determine the Environments (tools)
- Use Nodejs(expressJs)
- Use Typescript
- TypeORM (Postgres)

## 4. Schedule of implementation of the various parts
Below Tasks will be delivered by specified dates
- Implementation plan by Wednesday (22th/5/2024)
- API Implementation by Friday (24th/5/2024)
- API Documentation and Unit Testing by Friday (24th/5/2024)

## 5. Dependencies/Foreseen blockers from team members
None

## 6. External services or libraries to be used.
<img src="https://github.com/atlp-rwanda/knights-ecomm-be/assets/82057476/a42d3196-3140-4d16-8705-fa991f1492f9" alt="images" width="200">

**Comment by MC-Knight** [comment]
@faid-terence you can check on our implementation plan

**Comment by faid-terence** [comment]
@MC-Knight  and @GSinseswa721 Looks good !
Please start implementation , most people depend on your task !
