### ISSUE TITLE
Linting and Formatting

### ISSUE THREAD

**Issue by GSinseswa721** [atlp-rwanda/knights-ecomm-be#9]
- [ ]  Set up ESLint for code linting

- [ ]  Configure Prettier for code formatting

 

- [ ] Create .eslintrc and .prettierrc configuration files

- [ ]  Add lint and format scripts to package.json

**Comment by faid-terence** [comment]
@GSinseswa721 !
Please write a proper GitHub Issue[Here is a guide link](https://github.com/atlp-rwanda/engineering-playbook/wiki/4.1-GitHub-Issues-Guide)
