### ISSUE TITLE
Vendor - Order Management

### ISSUE THREAD

**Issue by faid-terence** [atlp-rwanda/knights-ecomm-be#92]
#### Description:
The backend must manage the retrieval and updating of order status information, Information retrieved will be used on frontend, This involves handling GET request to fetch order status and POST request to update order status by either admin or Vendor. The system should also push real-time updates to the frontend whenever the order status changes.

#### Acceptance Criteria:
- **GIVEN** a get request for order status information [Get single/ all order(s)]
  **WHEN** the requesting user/token is a admin or vendor the request is validated
  **THEN**: 
      The appropriate order status information should be retrieved from the database
      The order status information should be sent to the frontend to be displayed to the buyer
      [ For Admin ]: retrieve all orders in DB
      [ For Vendor]: retrieve all orders related to the vendor.

- **GIVEN** a post request to update order status
  **WHEN** the request body is validated and the requesting user/token is an admin/vendor
  **THEN**:
      The order status in the database should be updated [ Completed status is only set by admin ];
      The updated order status should be sent to the frontend to be displayed to the buyer

#### Dev notes:
- The order status should be updated in real-time using web sockets or similar technology
- The order status information should include the current status of the order and the expected delivery date
- The order status information should be accessible from the order history page, the order detail page, and a dedicated tracking page if available.

**Comment by faid-terence** [comment]
@aimedivin Please make a clear description and attach an implementation plan for this issue !

**Comment by aimedivin** [comment]
## Implementation plan
### 1. Deliverables at the end of the project.
The task will deliver API endpoints in two parties: one to get order status and another to update order status, with real-time updates using WebSocket. as these routes are protected, Security features will be added to verify user identity and permissions, and there will be checks to ensure the data sent in requests is correct.

#### DEV NOTE (REQUIRED)
#### Documentation: 
- API documentation for GET and POST endpoints using swagger.

### 2. Data flow / Flowchart / pseudocode / ERD diagrams
![diagram-export-5-22-2024-6_47_46-AM](https://github.com/atlp-rwanda/knights-ecomm-be/assets/82057476/3acde702-e922-41c6-938c-6f10eb8d3b6f)


### 3. Schedule of implementation of the various parts
- Complete Implementation plan by 21st / 05/ 2024
- Complete API development by 23rd / 05/ 2024
- Complete API unit testing by 24th / 05/ 2024) 
- Complete API documentation by 24th / 05/ 2024
- Have all functionalities 24/ 05/ 2024.

### 4. Dependencies/Foreseen blockers from team members
- #91 

### 5. External services or libraries to be used
- WebSocket Libraries: Socket.IO for real-time communication.
- Database: PostgreSQL for storing order data.
- Authentication: JWT for user authentication.
- Testing: Postman for API testing, Jest for unit testing.
